config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'welcome/index'

  resources :answers

  get '/questions/delete_connection', :to => 'questions#delete_connection'

  resources :questions

  devise_for  :users

  get '/quiz_round', :to => 'quiz_rounds#index'
  get '/quiz_round/new', :to => 'quiz_rounds#new'
  get '/quiz_round/false_round', :to => 'quiz_rounds#falseRound'
  get '/quiz_round/check', :to => 'quiz_rounds#check'
  get '/quiz_round/overview', :to => 'quiz_rounds#show'

  root 'welcome#index'

  get '*unmatched_route', :to => 'welcome#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :category_to_questions
  has_many :categories, through: :category_to_questions

  has_many :user_to_questions
  has_many :users, through: :user_to_questions

  validates :question, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_category_ids, only: [:new, :show]
  before_action :set_questions_and_categories, only: [:edit, :index, :new, :show, :create]

  def index
    if (params[:cats] != nil)
      @ownCategories = Array.new
      params[:cats].each do |cat_id|
        @ownCategories.push(Category.find(cat_id))
        @question_id = params[:quest]
      end
    end

    @search = Question.ransack(params[:q])
    # use ransacks params for array
    if (params[:q] != nil)
      @questions = check_question_role(Question).find_all { |quest| quest.question.downcase.include? ( params[:q][:question].to_s.downcase ) }
      @filterParams = params[:q][:question]
    end

    #respond_with(@questions)
  end

  def show
    if !(current_user.has_role?(@question.id.to_s + "_see") || current_user.has_role?(@question.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to questions_url
    end
  end

  def new
    @question = Question.new

    if(params[:question_text] != nil)
      setOldValues
    else
      # add default selected answer
      @correctValue1 = true
    end
    #respond_with(@question)
  end

  def edit
    if !( current_user.has_role?(@question.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to questions_url
    end

    if(params[:question_text] != nil)
      setOldValues
    else
      @answerValue1 = @question.answers[0].answer
      @correctValue1 = @question.answers[0].correctAnswer
      @answerValue2 = @question.answers[1].answer
      @correctValue2 = @question.answers[1].correctAnswer
      @answerValue3 = @question.answers[2] == nil ? nil : @question.answers[2].answer
      @correctValue3 = @question.answers[2] == nil ? false : @question.answers[2].correctAnswer
      @answerValue4 = @question.answers[3] == nil ? nil : @question.answers[3].answer
      @correctValue4 = @question.answers[3] == nil ? false : @question.answers[3].correctAnswer

      @question_text = @question.question
    end
  end

  def setOldValues
    @question_text = params[:question_text]
    @answerValue1 = params[:answer1]
    @answerValue2 = params[:answer2]
    @answerValue3 = params[:answer3]
    @answerValue4 = params[:answer4]

    @correctValue1 = params[:selected] == "correct1"
    @correctValue2 = params[:selected] == "correct2"
    @correctValue3 = params[:selected] == "correct3"
    @correctValue4 = params[:selected] == "correct4"
  end


  def create
    setVariables

    if check_guilty_answers

      @question = Question.new(question_params)

      if @question.save
        addCategories

        current_user.add_role(@question.id)

        if create_new_answer(@answerValue1, @question.id, @correctValue1) and create_new_answer(@answerValue2, @question.id, @correctValue2) and (create_new_answer(@answerValue3, @question.id, @correctValue3) or @answerValue3 == "") and (create_new_answer(@answerValue4, @question.id, @correctValue4) or @answerValue4 == "")
          respond_to do |format|
            if params[:commit] == "Save"
              @quest = Question.find(@question.id)
              format.html { redirect_to question_path(@quest), notice: 'Question successfully created!'}
              format.json { render :show, status: :created, location: @question }
            else
              format.html { redirect_to new_question_path(:cats=>params[:question][:id]), notice: 'Question successfully created!' }
              format.json { render :show, status: :created, location: @question }
            end

          end
        else
          @question.destroy
          flash[:warning] = 'Not enough answers.'
          redirect_to new_question_url(:question_text=>question_params[:question], :answer1=>@answerValue1, :answer2=>@answerValue2, :answer3=>@answerValue3, :answer4=>@answerValue4, :selected=>params[:question][:correctMethod])
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:warning] = 'Not enough or no correct answer.'
      redirect_to new_question_url(:question_text=>question_params[:question], :answer1=>@answerValue1, :answer2=>@answerValue2, :answer3=>@answerValue3, :answer4=>@answerValue4, :selected=>params[:question][:correctMethod])
    end

    # respond_with(@question)
  end

  def create_new_answer(answer, questionId, correct)
    newAnswer = {'answer' => answer, 'question_id' => questionId, 'correctAnswer' => correct}
    return Answer.new(newAnswer).save
  end

  def check_guilty_answers()
    return (@answerValue1 != "" and @answerValue2 != "" and (@correctValue1 or @correctValue2 or (@answerValue3 != "" and @correctValue3) or (@answerValue4 != "" and @correctValue4)))
  end

  def update
    if !(current_user.has_role?(@question.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to questions_url
    end

    setVariables

    if (check_guilty_answers)
      answer_params = {1 => {'answer' => @answerValue1, 'correctAnswer' => @correctValue1},
                       2 => {'answer' => @answerValue2, 'correctAnswer' => @correctValue2},
                       3 => {'answer' => @answerValue3, 'correctAnswer' => @correctValue3},
                       4 => {'answer' => @answerValue4, 'correctAnswer' => @correctValue4}}

      noError = true

      index = 1
      @question.answers.each do |ans|
        if (answer_params[index]['answer'] == "" and index > 2)
          noError = noError ? ans.delete : false
        else
          if (answer_params[index]['answer'] == "" and index <= 2)
            noError = false
          else
            ans.delete
            noError = noError ? create_new_answer(answer_params[index]['answer'], @question.id, answer_params[index]['correctAnswer']) : false
          end
        end
        index = index + 1
      end

      #maybe add new answers
      if (index == 3 and answer_params[3]['answer'] != "")
        noError = noError ? create_new_answer(answer_params[3]['answer'], @question.id, answer_params[3]['correctAnswer']) : false
        index = index + 1
      end

      if (index == 4 and  answer_params[4]['answer'] != "")
        noError = noError ? create_new_answer(answer_params[4]['answer'], @question.id, answer_params[4]['correctAnswer']) : false
      end

      removeCategories
      addCategories

      # respond_to do |format|
        if @question.update(question_params)
          if noError
            flash[:notice] = 'Question successfully updated!'
            if params[:commit] == "Save"
              redirect_to edit_question_url
            else
              redirect_to new_question_path(:cats=>params[:question][:id])
            end
          else
            flash[:warning] = 'Not enough or no correct answer.'
            redirect_to edit_question_url(:question_text=>question_params[:question], :answer1=>@answerValue1, :answer2=>@answerValue2, :answer3=>@answerValue3, :answer4=>@answerValue4, :selected=>params[:question][:correctMethod])
          end
        else
          flash[:notice] = 'No question text!'
          redirect_to edit_question_url(:question_text=>question_params[:question], :answer1=>@answerValue1, :answer2=>@answerValue2, :answer3=>@answerValue3, :answer4=>@answerValue4, :selected=>params[:question][:correctMethod])
        end
    else
      flash[:warning] = 'Not enough or no correct answer.'
      redirect_to edit_question_url(:question_text=>question_params[:question], :answer1=>@answerValue1, :answer2=>@answerValue2, :answer3=>@answerValue3, :answer4=>@answerValue4, :selected=>params[:question][:correctMethod])
    end

    #respond_with(@question)
  end

  def destroy
    if !(current_user.has_role?(@question.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to questions_url
    end

    ownCategories = Array.new

    @question.categories.each do |cat|
      if current_user.has_role?(cat.name + cat.id.to_s) || current_user.has_role?(:admin)
        ownCategories.push(cat)
      end
    end

    if ownCategories.length == 0 && !@question.categories.empty?
      flash[:warning] = 'Permission denied, you are not the owner of the categories'
      redirect_to questions_url
    else
      if ownCategories.length == 1 || @question.categories.empty?
        removeCategories

        @question.answers.each do |ans|
          ans.destroy
        end

        Role.destroy_all(:name => @question.id.to_s)
        Role.destroy_all(:name => @question.id.to_s + "_see")

        @question.destroy

        respond_to do |format|
          format.html { redirect_to questions_url, notice: 'Question successfully deleted!' }
          format.json { head :no_content }
        end
      else
        redirect_to questions_url(:cats => ownCategories, :quest => @question.id)
      end
    end
  end

  def setVariables()
    @answerValue1 = params[:question][:answers1]
    @correctValue1 = params[:question][:correctMethod] == "correct1"
    @answerValue2 = params[:question][:answers2]
    @correctValue2 = params[:question][:correctMethod] == "correct2"
    @answerValue3 = params[:question][:answers3]
    @correctValue3 = params[:question][:correctMethod] == "correct3"
    @answerValue4 = params[:question][:answers4]
    @correctValue4 = params[:question][:correctMethod] == "correct4"
  end

  def removeCategories
    @question.category_to_questions.destroy_all
  end

  def addCategories
    params[:question][:id].each do |id|
      if id != ""
        CategoryToQuestion.new({'category_id' => id, 'question_id' => @question.id}).save
      end
    end
  end

  def delete_connection

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
            <% @question.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :question %><br>
      <%= f.text_field :question, :value => @question_text, class: "form-control" %> <br>

      <%= f.label :please_insert_the_answers_and_select_the_correct_one %>
      <table style="width: 100%" >
        <tr class="table_row">
          <td><%= f.text_field :answers1, :value => @answerValue1, class: "form-control" %></td>
          <td class="questions_radio"><%= f.radio_button :correctMethod, :correct1, :checked => @correctValue1 %></td>
          <td><%= f.text_field :answers2, :value => @answerValue2, class: "form-control" %></td>
          <td class="questions_radio"><%= f.radio_button :correctMethod, :correct2, :checked => @correctValue2 %></td>
        </tr>
        <tr><td></td><td></td></tr>
        <tr class="table_row">
          <td><%= f.text_field :answers3, :value => @answerValue3, class: "form-control" %></td>
          <td class="questions_radio"><%= f.radio_button :correctMethod, :correct3, :checked => @correctValue3 %></td>
          <td><%= f.text_field :answers4, :value => @answerValue4, class: "form-control" %></td>
          <td class="questions_radio"><%= f.radio_button :correctMethod, :correct4, :checked => @correctValue4 %></td>
        </tr>
      </table><br>
      <%= f.label :categories %><br>
      <%= f.collection_select :id, @categories, :id, :name, { selected: @categories_ids }, {class: "form-control", multiple: "true" } %>
    </div>
    <div class="actions align-right">
      <%= f.submit "Save and new question", class: "btn btn-success" %>
      <%= f.submit :Save, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/questions/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Editing Questions</h4>
  </div>
  <div class="panel-body">

<%= render 'form' %>


  </div>
</div>
<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>

app/views/questions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Question overview
      <% if @filterParams != nil %>
          <span class="filtered">(filtered by "<%= @filterParams %>")</span>
      <% end %></h4>
  </div>
  <div class="panel-body">

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
            <td width="300"><%= link_to 'Show', question, class: 'btn btn-default fa fa-eye' %>
         <% if current_user.has_role?(question.id.to_s) || current_user.has_role?(:admin) %>
            <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-default fa fa-pencil' %>
            <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default fa fa-trash-o' %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

    <%= search_form_for @search do |f| %>
        <div class="search_container field">
          <%= f.label :question, "Question" %>
          <%= f.text_field :question %>
          <%= f.submit "Search", class: "btn btn-success "  %>

          <% if @filterParams != nil %>
              <%= link_to "Deactivate", questions_path, class: 'btn btn-danger' %>
          <% end %>
        </div>
    <% end %>

     <% if @ownCategories != nil %>
        <div id="overlay" >
          <div id="overlay_inner" class="panel panel-default">
            <div class="panel-heading">
                <h4 style="text-align:center">Conntected categories</h4>
            </div>
            <div class="panel-body">
            <% @ownCategories.each do |cat| %>
                <div  class="one_category">
                    <div class="float_left" id="<%= cat.id %>"><%= cat.name %></div>
                    <%= link_to 'Delete', questions_delete_connection_path(:cat=>cat.id, :quest=>@question_id), class: 'btn btn-danger float_left' %>
                </div>
            <% end %>
            </div>
            </div>
        </div>
    <% end %>

<br>

<%= link_to 'New Question', new_question_path, class: 'btn btn-primary align-right' %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Create a new question</h4>
  </div>
  <div class="panel-body"> <%= render 'form' %></div>
</div>

<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>

app/views/questions/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 style="display: inline;"><%= @question.question %></h4>
  </div>
  <div class="panel-body">

    <strong>Answers:</strong>
      <% index = 1 %>
      <% @question.answers.each do |ans| %>
        <div <% if ans.correctAnswer %>
             style="background-color: #00CD00;"
            <% end %>>
        <%= index %>. <%= ans.answer %>
        <% index = index + 1 %>
        </div>
      <% end %><br><p>
    <strong>Categories of Question:</strong> <br>
    <% index = 1
       @question.categories.all.each do |cat| %>
        <%= index %>.  <%= link_to cat.name, cat%> <br>
        <% index = index + 1
       end %>
    <div class="align-right">
      <% if current_user.has_role?(@question.id.to_s + "_full") || current_user.has_role?(:admin) %>
        <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-primary fa fa-pencil'%>
      <% end %>
      <% if current_user.has_role?(@question.id.to_s) || current_user.has_role?(:admin) %>
        <%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger fa fa-trash-o' %></td>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>