config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'welcome/index'

  resources :answers

  get '/questions/delete_connection', :to => 'questions#delete_connection'

  resources :questions

  devise_for  :users

  get '/quiz_round', :to => 'quiz_rounds#index'
  get '/quiz_round/new', :to => 'quiz_rounds#new'
  get '/quiz_round/false_round', :to => 'quiz_rounds#falseRound'
  get '/quiz_round/check', :to => 'quiz_rounds#check'
  get '/quiz_round/overview', :to => 'quiz_rounds#show'

  root 'welcome#index'

  get '*unmatched_route', :to => 'welcome#index'

end

app/models/quiz_round.rb
class QuizRound < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  belongs_to :question
end

app/controllers/quiz_rounds_controller.rb
class QuizRoundsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category])

    if params[:question] != nil
      @question = Question.find(params[:question])
      @answerChoose = 1
      @selectedAnswer = params[:selectedAnswer]
    else
      @answerChoose = 0
      @selectedAnswer = 1

      questions = getQuestions(@category)

      length = questions.count

      if length == 0
        #all questions done
      else
        @question = questions[rand(length)]
      end
    end
  end

  def getQuestions(category)
    children = check_category_role(Category).select {|parent| parent.parent_id == category.id}
    questions = category.questions

    #get questions from children
    children.each do |child|
      questions = questions + child.questions
    end

    answeredQuestion = Array.new

    QuizRound.where("category_id" => category.id, "user_id" => current_user.id).map(&:question).each do |rem|
      answeredQuestion.push(rem)
    end

    questions = questions - answeredQuestion

    return questions
  end

  def new
    categoryId = params[:category]
    QuizRound.where("category_id" => categoryId, "user_id" => current_user.id).destroy_all

    redirect_to quiz_round_url(:category=> categoryId)
  end

  def check
    categoryId = params[:category]
    questionId = params[:question]

    question = Question.find(params[:question])

    correct = false
    index = 1
    question.answers.each do |ans|
      if index == params[:selectedAnswer].to_i && ans.correctAnswer
        correct = true
      end
      index = index + 1
    end

    QuizRound.create("category_id" => categoryId, "question_id" => questionId, "user_id" => current_user.id, "correct" => correct)

    redirect_to quiz_round_url(:category=> categoryId, :question=>questionId, :selectedAnswer => params[:selectedAnswer])
  end

  def falseRound
    categoryId = params[:category]
    questions = getQuestions(Category.find(categoryId))

    # set not answered questions as correct
    questions.each do |quest|
      QuizRound.create("category_id" => categoryId, "question_id" => quest.id, "user_id" => current_user.id, "correct" => true)
    end

    # remove all false questions
    QuizRound.where("category_id" => categoryId, "user_id" => current_user.id, "correct" => false).destroy_all

    redirect_to quiz_round_url(:category=> categoryId)
  end

  def show
    @categories = check_category_role(Category)
  end

end

app/views/quiz_rounds/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Quiz-Round <%= @category.name %></h4>
  </div>
  <div class="panel-body" id="quiz_rounds_answer_container">
    <% if @question == nil %>
        No more questions
    <% else %>
        <%= @question.question %>
        <% index = 1 %>
        <% @question.answers.each do |ans| %>
            <div class="answer_container" <% if ans.correctAnswer && @answerChoose == 1 %>
                    style="background-color: #00CD00;"
                 <% else if index == @selectedAnswer.to_i && @answerChoose == 1 %>
                    style="background-color: #cd0000;"
                 <% end end %>>
              <%= radio_button(:select, :question, index.to_s, {:checked => index == @selectedAnswer.to_i, :class => "checked_radio"}) %>
              <%= ans.answer %>
              <% index = index + 1 %>
            </div>
        <% end %>

        <% if @answerChoose != 1 %>
            <%= link_to "Check Answer", quiz_round_check_url(:question => @question.id, :category => @category.id, :selectedAnswer => @selectedAnswer), {class: "btn btn-primary", id: "btn_check"} %>
        <% end %>
        <%= link_to "Next Questions", quiz_round_url(:category => @category.id), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= link_to 'Back', quiz_round_overview_path, :class => "fa fa-arrow-circle-o-left" %>

app/views/quiz_rounds/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Choose a category and start your quiz!</h4>
  </div>
  <div class="panel-body">

    <table class="table table-striped">
      <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Subject</th>
        <th colspan="4"></th>
      </tr>
      </thead>

      <tbody>
      <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= parent = @categories.detect{|c| c.id == category.parent_id}
                    if category.parent_id != nil && parent != nil
                      parent.name
                    end %></td>
            <td width="400"><%= link_to 'Start new Quiz', quiz_round_new_path(:category => category), class: 'btn btn-default' %>
              <%= link_to 'Continue Quiz', quiz_round_path(:category => category), class: 'btn btn-default' %>
              <%= link_to 'Checking', quiz_round_false_round_path(:category => category), class: 'btn btn-default' %>
            </td>

          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Category', new_category_path, class: 'btn btn-primary align-right' %>
  </div>
</div>