config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'welcome/index'

  resources :answers

  get '/questions/delete_connection', :to => 'questions#delete_connection'

  resources :questions

  devise_for  :users

  get '/quiz_round', :to => 'quiz_rounds#index'
  get '/quiz_round/new', :to => 'quiz_rounds#new'
  get '/quiz_round/false_round', :to => 'quiz_rounds#falseRound'
  get '/quiz_round/check', :to => 'quiz_rounds#check'
  get '/quiz_round/overview', :to => 'quiz_rounds#show'

  root 'welcome#index'

  get '*unmatched_route', :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :category
  has_many :category_to_questions
  has_many :questions, through: :category_to_questions

  has_many :user_to_categories
  has_many :users, through: :user_to_categories

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_questions_and_categories, only: [:show, :create]
  before_action :set_questions_and_categories_only_full_access, only: [:new, :edit, :update]
  before_action :set_role_user, only: [:edit, :show, :new, :update, :create]

  def index
    @search = Category.ransack(params[:q])
    # use ransacks params for array
    if (params[:q] != nil)
      @categories = check_category_role(Category).find_all { |cat| cat.name.downcase.include? ( params[:q][:name].to_s.downcase ) }
      @filterParams = params[:q][:name]
    else
      @categories = check_category_role(Category)
    end
   #respond_with(@categories)
  end

  def show
    if !(current_user.has_role?(@category.name + @category.id.to_s + "_see") ||current_user.has_role?(@category.name + @category.id.to_s + "_full") || current_user.has_role?(@category.name + @category.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to categories_url
    end

    @children = check_category_role(Category).select {|parent| parent.parent_id == @category.id}
  end

  def new
    @category = Category.new
    #respond_with(@category)
  end

  def edit
    if !(current_user.has_role?(@category.name + @category.id.to_s + "_full") || current_user.has_role?(@category.name + @category.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to categories_url
    end
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        addQuestions
        create_roles

        current_user.add_role(@category.name + @category.id.to_s)

        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    #respond_with(@category)
  end

  def update
    if !(current_user.has_role?(@category.name + @category.id.to_s + "_full") || current_user.has_role?(@category.name + @category.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to categories_url
    end

    respond_to do |format|

      # do it simple remove first all relations between this category and the questions
      removeQuestions
      addQuestions

      if @category.update(category_params)
        create_roles

        format.html { redirect_to categories_url, notice: 'Category was successfully updated.'}
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    #respond_with(@category)
  end

  def destroy_questions_roles
    @category.questions.each do |quest|
      Role.destroy_all(:name => quest.id.to_s + "_see")
      Role.destroy_all(:name => quest.id.to_s + "_full")
    end
  end

  def create_roles()
    Role.destroy_all(:name => @category.name  + @category.id.to_s + "_see")
    Role.destroy_all(:name => @category.name  + @category.id.to_s + "_full")

    destroy_questions_roles

    usersWithFullAccess = params[:list_with_full_access][:id]
    usersWithAccessToShow = params[:list_with_access_to_show][:id]

    @category.questions.each do |quest|
      set_roles(usersWithFullAccess, quest.id.to_s)
      set_roles(usersWithAccessToShow, quest.id.to_s + "_see")

      @owner.add_role(quest.id.to_s)
    end

    set_roles( usersWithFullAccess, @category.name + @category.id.to_s + "_full" )
    set_roles( usersWithAccessToShow, @category.name + @category.id.to_s + "_see" )
  end

  def set_roles(list, typ)
    if list != nil
      list.each do |id|
        if id != ""
          User.find(id.to_i).add_role(typ)
        end
      end
    end
  end

  def destroy
    if !(current_user.has_role?(@category.name + @category.id.to_s) || current_user.has_role?(:admin))
      flash[:warning] = 'Permission denied'
      redirect_to categories_url
    end

    flag = false

    Category.all.each do |category|
      if category.parent_id == @category.id
        flag = true
      end
    end

    if !flag
      removeQuestions

      Role.destroy_all(:name => @category.name + @category.id.to_s)
      Role.destroy_all(:name => @category.name + @category.id.to_s + "_see")
      Role.destroy_all(:name => @category.name + @category.id.to_s + "_full")

      destroy_questions_roles

      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:warning] = 'Category can not destroyed because it is a parent category.'
      redirect_to categories_url

    end

    #respond_with(@category)
  end

  def removeQuestions
    @category.category_to_questions.destroy_all
  end

  def addQuestions
    questions = params[:category][:questions]

    questions.each do |id|
      if id != ""
        CategoryToQuestion.new({'category_id' => @category.id, 'question_id' => id}).save
      end
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def set_questions_and_categories
    @questions = check_question_role(Question)
    @categories = check_category_role(Category)
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end

  def set_role_user
    @usersWithoutRole = Array.new

    User.all.each do |user|
      @usersWithoutRole.push( user )
    end


    if(@category != nil)
      @usersWithFullAccess = User.with_role (@category.name + @category.id.to_s + "_full")
      @usersWithSeeAccess = User.with_role (@category.name + @category.id.to_s + "_see")

      @usersWithFullAccess.each do |rem|
        @usersWithoutRole.delete(rem)
      end

      @usersWithSeeAccess.each do |rem|
        @usersWithoutRole.delete(rem)
      end

      @owner = User.with_role(@category.name + @category.id.to_s).first
    else
      @usersWithFullAccess = Array.new
      @usersWithSeeAccess = Array.new
      @owner = current_user
    end

    @usersWithoutRole.delete(@owner)

  end

  def set_questions_and_categories_only_full_access
    @questions = check_question_role_only_full_access(Question)
    @categories = check_category_role_only_full_access(Category)

    if (@category != nil)
      parent_id = @category.parent_id
      if parent_id != nil
        parent = Category.find(parent_id)
        if !(current_user.has_role?(parent.name + parent.id.to_s) || current_user.has_role?(parent.name + parent.id.to_s + "_full") || current_user.has_role?(parent.name + parent.id.to_s + "_see"))
          @categories.push(parent)
        end
      end

      @categories.delete(@category)
    end


  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name, class: "form-control" %>
      <br>
      <%= f.label :subject %>
      <br>
           <%= f.collection_select :parent_id, @categories, :id, :name, {selected: @category.parent_id, :include_blank => true}, class: "form-control" %>

          <br>
      <strong>Owner: </strong> <%= @owner.email %>
      <br><br>
      <%= f.label :selected_questions %><br>
      Double-click to show question in detail
      <%= f.collection_select :questions, @category.questions, :id, :question, {}, { multiple: true, class: "form-control"  }%>

      <br>
      <div align="center">
         <button id="btn_select" class="btn btn-success fa fa-arrow-up">Select</button>
         <button id="btn_deselect" class="btn btn-warning fa fa-arrow-down">Deselect</button>
         <%= link_to 'New Question', new_question_path(:category_id=>@category.id), class: 'btn btn-primary fa fa-plus' %>
      </div>
      <br>
      <%= f.label :other_questions %><br>
      Double-click to show question in detail
      <select class="form-control" id="unused_questions" multiple="multiple">
      <optgroup value="category" label="Questions without Category"/>
      <% @questions.each do |quest|
            if quest.categories.empty? %>
              <option value="<%= quest.id %>"><%= quest.question  %></option>
            <% end
         end
         @categories.each do |cat| %>
           <% if !cat.questions.empty? && cat.id != @category.id %>
             <optgroup value="category" label="Questions of Category: <%= cat.name %>"/>
             <% cat.questions.all.each do |quest| %>
                <option value="<%= quest.id %>"><%= quest.question  %></option>
             <%
                end
           end
          end
       %>
       </select>
<br><br>
      <div><h4>Determine access rights</h4></div>
    <div>
        <div class="selectbox">
            <label>Full access User</label><br>
          Create, Read, Update<br>
            <%= f.collection_select :id, @usersWithFullAccess, :id, :email, {}, { id: "list_with_full_access", multiple: true, name: "list_with_full_access[id][]"} %>
            <div class="move_button_container">
                <div class="move_button_container_inside">
                  <button id="to_list_with_full_access" class="move_button"><<</button>
                    <button id="from_list_with_full_access" class="move_button">>></button>
                  </div>
            </div>

        </div>
        <div class="selectbox">
          <label>Limited access User</label><br>
          Read<br>
            <%= f.collection_select :id, @usersWithSeeAccess, :id, :email, {}, { id: "list_with_access_to_show", multiple: true, name: "list_with_access_to_show[id][]"} %>
          <div class="move_button_container">
            <div class="move_button_container_inside">
                <button id="from_list_without_access" class="move_button"><<</button>
                <button id="to_list_without_access" class="move_button">>></button>
            </div>
          </div>
        </div>


        <div class="selectbox">
          <label>List of all members<br></label>
          <br><br>
            <%= f.collection_select :id, @usersWithoutRole, :id, :email, {}, { id: "list_without_access", multiple: true, name: "list_without_access"} %>
        </div>
    </div>
    </div>
    <div class="actions">
      <%= f.submit :Save, {class: "btn btn-primary align-right ", id: "btn_submit" } %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Editing Category</h4>
  </div>
  <div class="panel-body"> <%= render 'form' %></div>


</div>

<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>

app/views/categories/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Category overview
    <% if @filterParams != nil %>
      <span class="filtered">(filtered by "<%= @filterParams %>")</span>
    <% end %>
    </h4>
  </div>
  <div class="panel-body">

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Counter questions</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= parent = @categories.detect{|c| c.id == category.parent_id}
            if category.parent_id != nil && parent != nil
              link_to parent.name, category_path(parent)
            end %></td>
        <td style="text-align: center;"><%= category.questions.count %></td>
        <td width="300"><%= link_to 'Show', category, class: 'btn btn-default fa fa-eye' %>
          <% if current_user.has_role?(category.name + category.id.to_s ) || current_user.has_role?(category.name + category.id.to_s + "_full") || current_user.has_role?(:admin) %>
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-default fa fa-pencil' %>
          <% end %>
          <% if current_user.has_role?(category.name + category.id.to_s ) || current_user.has_role?(:admin) %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default fa fa-trash-o' %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

    <div class="field search_container">
        <%= search_form_for @search do |f| %>
          <%= f.label :name, "Name" %>
          <%= f.text_field :name %>
          <%= f.submit "Search", class: "btn btn-success "  %>

          <% if @filterParams != nil %>
              <%= link_to "Deactivate", categories_path, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
    </div>
<%= link_to 'New Category', new_category_path, class: 'btn btn-primary align-right' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>New Category</h4>
  </div>
  <div class="panel-body"> <%= render 'form' %></div>
</div>


<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4 style="display: inline;">Category: <%= @category.name %></h4>
  </div>
  <div class="panel-body"><strong>Subject:</strong>
    <% parent = @categories.detect{|c| c.id == @category.parent_id}
        if @category.parent_id != nil && parent != nil %>
        [<%= @category.parent_id %>]
        <%= link_to parent.name, parent %>
        <% end %>
    <p><br>
      <strong>Owner: </strong> <%= @owner.email %>
      <br><br>
      <strong>Underlings Categories: </strong><br>

      <% @children.each do |cat| %>
          <%= link_to cat.name, cat %><br>
      <% end %>
      <br>
    <strong>Questions of Category:</strong> <br>
    <% index = 1
       @category.questions.all.each do |quest| %>
         <%= index %>.  <%= link_to quest.question, quest%> <br>
         <% index = index + 1
       end %>
      <div>
        <div class="selectbox">
          <label>User with full access</label>
          <%= collection_select :id, :id, @usersWithFullAccess, :id, :email, {}, { id: "list_with_full_access", multiple: true, name: "list_with_full_access[id][]"} %>
        </div>
        <div class="selectbox">
          <label>Users with access to see </label>
          <%= collection_select :id, :id, @usersWithSeeAccess, :id, :email, {}, { id: "list_with_access_to_show", multiple: true, name: "list_with_access_to_show[id][]"} %>
        </div>
        <div class="selectbox">
          <label>Users without roles</label>
          <%= collection_select :id, :id, @usersWithoutRole, :id, :email, {}, { id: "list_without_access", multiple: true, name: "list_without_access"} %>
        </div>
      </div>

        <div class="align-right">
          <% if current_user.has_role?(@category.name + @category.id.to_s + "_full") || current_user.has_role?(:admin) %>
           <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-primary fa fa-pencil" %>
          <% end %>
          <% if current_user.has_role?(@category.name + @category.id.to_s ) || current_user.has_role?(:admin) %>
           <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger fa fa-trash-o'  %>
          <% end %>
        </div>
      </div>
</div>



<%= link_to 'Back', :back , :class => "fa fa-arrow-circle-o-left btn btn-default"  %>