config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'welcome/index'

  resources :answers

  get '/questions/delete_connection', :to => 'questions#delete_connection'

  resources :questions

  devise_for  :users

  get '/quiz_round', :to => 'quiz_rounds#index'
  get '/quiz_round/new', :to => 'quiz_rounds#new'
  get '/quiz_round/false_round', :to => 'quiz_rounds#falseRound'
  get '/quiz_round/check', :to => 'quiz_rounds#check'
  get '/quiz_round/overview', :to => 'quiz_rounds#show'

  root 'welcome#index'

  get '*unmatched_route', :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FantasticQuiz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render partial: 'shared/navigation' %>
    <div class="container">
      <div id="js_notice" class="alert alert-warning">Javascript is disabled in your web browser. You have to enable JavaScript to use this site correctly.</div>

      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <% if current_user %>
        <div class="col-lg-3">
          <div class="well sidebar-nav navbar-top">
            <h3>Actions</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Create a new category", new_category_path , :class => "fa fa-plus" %></li>
              <li><%= link_to "Create a new question", new_question_path , :class => "fa fa-plus" %></li>
              <li><%= link_to "Categories overview", categories_path  , :class => "fa fa-bars" %></li>
              <li><%= link_to "Questions overview", questions_path , :class => "fa fa-bars"  %></li>
              <li><%= link_to "Start a quiz", quiz_round_overview_path , :class => "fa fa-play-circle" %></li>
            </ul>
          </div><!--/.well -->

          <% if current_user.has_role?(:admin) %>

              <div class="well sidebar-nav navbar-top">
                <h3>Statistics</h3>
                <ul class="nav nav-list">
                  <li>User: <%= User.all.count %></li>
                  <li>Categories: <%= Category.all.count %></li>
                  <li>Questions: <%= Question.all.count %></li>
                </ul>
              </div><!--/.well -->

          <% end %>

        </div><!--/span-->


        <% end %>
      </div><!--/row-->

      <footer>
        <p>&copy; Fanstatic.Quiz 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>